FROM openjdk:17-jdk-slim

WORKDIR /app

COPY api/mvnw .
COPY api/.mvn .mvn
COPY api/pom.xml .
COPY api/src ./src

RUN chmod +x ./mvnw

RUN ./mvnw dependency:go-offline -B

RUN ./mvnw clean package -DskipTests

RUN cp target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
