FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY api/mvnw .
COPY api/.mvn .mvn
COPY api/pom.xml .

RUN chmod +x ./mvnw

RUN ./mvnw dependency:go-offline -B

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dspring.profiles.active=development"]
