
services:
  postgres:
    image: postgres:16-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-network

  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend
    container_name: banking-backend
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mySecretKey
      CORS_ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - banking-network

  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.frontend
    container_name: banking-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge
