services:
  postgres:
    image: postgres:16-alpine
    container_name: banking-postgres-dev
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking-network

  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend.dev
    container_name: banking-backend-dev
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking
      SPRING_DATASOURCE_USERNAME: banking_user
      SPRING_DATASOURCE_PASSWORD: banking_password
      JWT_SECRET: mySecretKey
      CORS_ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - "8080:8080"
    volumes:
      - ../../api/src:/app/src
      - /app/target
      - /app/.m2
    depends_on:
      - postgres
    networks:
      - banking-network

  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.frontend.dev
    container_name: banking-frontend-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4200:4200"
    volumes:
      - ../../web:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge
