services:
  - type: web
    name: banking-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./infra/docker/Dockerfile.backend
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: banking-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: banking-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: banking-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: SERVER_PORT
        value: "10000"
      - key: CORS_ALLOWED_ORIGINS
        value: https://banking-frontend.onrender.com
    autoDeploy: true

  - type: web
    name: banking-frontend
    runtime: static
    buildCommand: |
      cd web && 
      npm ci && 
      npm run build
    staticPublishPath: ./web/dist/banking
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /api/*
        destination: https://banking-backend.onrender.com/api/*
    autoDeploy: true

databases:
  - name: banking-db
    plan: starter
    databaseName: banking
    user: banking_user
